// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MessageClientInterface is an autogenerated mock type for the MessageClientInterface type
type MessageClientInterface struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: channel, message
func (_m *MessageClientInterface) SendMessage(channel string, message string) (interface{}, error) {
	ret := _m.Called(channel, message)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, string) interface{}); ok {
		r0 = rf(channel, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(channel, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
